### PR TITLE
Allow the second argument to be an array of ranges

### PR DESCRIPTION
**Pull request by deanwilson**
This allows you to specify an array of ranges
and return true if the IP address is present in any of them

### CODE REVIEW

**Comment by deanwilson** [comment]
This should address issue #7

**Comment by cwseys** [comment]
Hi Dean,
  Thanks for the arrayizing!  It will be really helpful.
  Unfortunately it doesn't quite work yet:

`ip_in_range($routed_ip,["144.92.180.0/23", "10.128.198.0/24", "128.104.227.0/24"])`

gives error
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, ip_in_range(): [["144.92.180.0/23", "10.128.198.0/24", "128.104.227.0/24"]] is an invalid ip address at /etc/puppet/environments/c2/modules/network/manifests/routes.pp:37:14 on node tardis01.physics.wisc.edu
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

(Looks like the array is inserted into another array.)

Chad.

**Comment by deanwilson** [comment]
Did you restart the puppet master once you updated the functions code? That error looks like what I was getting before I made the changes.

**Comment by cwseys** [comment]
Dang, I bet I'm not using the correct code.  How do I clone the new code?  Looks like I've just got the master branch from git clone https://github.com/deanwilson/puppet-ip_in_range.git
git branch -l
* master
P.S.  Looks like someone else thought this a good idea:
https://github.com/Saford91/puppet-ip_in_range/commit/71d5e68fc1c0bda658211db7ad3f1f10a41e2fa9

**Comment by deanwilson** [comment]
https://github.com/deanwilson/puppet-ip_in_range/blob/34fc61563bd12af99a389153707616557746963b/lib/puppet/parser/functions/ip_in_range.rb should contain the fix.

Forks are always welcome, hopefully once I've managed to address your request there won't be so much of a need for the current one.

**Comment by cwseys** [comment]
Yay!  It works!  Thanks, that will simplify the puppet code!

**Pull request merged**
